apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-demo
  template:
    metadata:
      labels:
        app: redis-demo
    spec:
      containers:
        - name: redis
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/redis:7.2
          ports:
            - containerPort: 6379
